services:
  private-app:
    build: ./private-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://private-app:9090/health"]
      interval: 10s
      timeout: 10s
      retries: 3
  exposed-app:
    depends_on:
      private-app:
        condition: service_healthy
    build: ./exposed-app
    ports:
      - 4242:8080
